# Project identification
sonar.projectKey=dpw_foundation_dpw_foundation_admin_96c92881-f8be-4066-91ea-c5b50e0f837d
sonar.projectName=Dpw_Foundation_Admin
sonar.projectVersion=1.0

# Source code
sonar.sources=src
sonar.inclusions=**/*.js,**/*.jsx,**/*.ts,**/*.tsx
sonar.exclusions=**/node_modules/**,**/*.test.js,**/*.test.jsx,**/*.test.ts,**/*.test.tsx

# Test files to exclude
sonar.test.exclusions=**/*.test.js,**/*.test.jsx,**/*.test.ts,**/*.test.tsx

# Code coverage report
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
